import { canonicalDescriptionJson, type TestDescription, type TypedValue } from "../description.js";
import { driverClassName } from "./java-driver.js";

/**
 * 生成完整 .cs 驱动源码(public class Driver_<hash>,内嵌 JsonWriter 与字面量 helper)。
 * 确定性:同一描述两次生成字节相同(driverClassName 基于 canonicalDescriptionJson 的 sha256)。
 */
export function generateCSharpDriver(description: TestDescription): string {
  const className = driverClassName(description);
  const lines: string[] = [];
  lines.push("// Generated by @forexplore/translation-verifier. Do not edit.");
  lines.push("using System;");
  lines.push("using System.Collections.Generic;");
  lines.push("");
  lines.push(`public class ${className} {`);
  lines.push(`  public static void Main(string[] args) {`);
  lines.push(`    var writer = new JsonWriter(System.Console.Out);`);
  lines.push(`    writer.BeginObject().Name("results").BeginArray();`);
  description.cases.forEach((_, i) => lines.push(`    Case_${String(i).padStart(3, "0")}(writer);`));
  lines.push(`    writer.EndArray().EndObject().Flush();`);
  lines.push(`  }`);
  lines.push(``);

  description.cases.forEach((c, i) => {
    const methodName = `Case_${String(i).padStart(3, "0")}`;
    lines.push(`  static void ${methodName}(JsonWriter writer) {`);
    lines.push(`    writer.BeginObject().Name("caseId").Value(${csharpStringLiteral(c.id)});`);
    const args = c.inputs.map(csharpLiteral).join(", ");
    const call = description.target.isStatic
      ? `${description.target.className}.${description.target.method}(${args})`
      : `new ${description.target.className}(${description.target.constructorArgs.map(csharpLiteral).join(", ")}).${description.target.method}(${args})`;
    lines.push(`    try {`);
    lines.push(`      var r = ${call};`);
    lines.push(`      writer.Name("outcome").Value("return");`);
    lines.push(`      writer.Name("returnValue");`);
    lines.push(`      WriteValue(writer, r);`);
    lines.push(`    } catch (System.Exception t) {`);
    lines.push(`      writer.Name("outcome").Value("exception");`);
    lines.push(`      writer.Name("exceptionType").Value(t.GetType().Name);`);
    lines.push(`      writer.Name("exceptionMessage").Value(t.Message ?? "");`);
    lines.push(`    }`);
    lines.push(`    writer.EndObject();`);
    lines.push(`  }`);
    lines.push(``);
  });

  lines.push(`  static void WriteValue(JsonWriter writer, object? value) {`);
  lines.push(`    if (value == null) { writer.BeginObject(); writer.Name("type").Value("null").Name("value").ValueNull(); writer.EndObject(); return; }`);
  lines.push(`    if (value is string s) { writer.BeginObject(); writer.Name("type").Value("string").Name("value").Value(s); writer.EndObject(); return; }`);
  lines.push(`    if (value is bool b) { writer.BeginObject(); writer.Name("type").Value("boolean").Name("value").Value(b); writer.EndObject(); return; }`);
  lines.push(`    if (value is int || value is long || value is short || value is byte || value is sbyte || value is uint || value is ushort || value is ulong) {`);
  lines.push(`      writer.BeginObject();`);
  lines.push(`      writer.Name("type").Value("number").Name("value").Value(System.Convert.ToInt64(value));`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value is double d) {`);
  lines.push(`      writer.BeginObject();`);
  lines.push(`      writer.Name("type").Value("number").Name("value").Value(d);`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value is float f) {`);
  lines.push(`      writer.BeginObject();`);
  lines.push(`      writer.Name("type").Value("number").Name("value").Value((double) f);`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value is decimal m) {`);
  lines.push(`      writer.BeginObject();`);
  lines.push(`      writer.Name("type").Value("number").Name("value").Value((double) m);`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value is System.Collections.IDictionary dict) {`);
  lines.push(`      writer.BeginObject();`);
  lines.push(`      writer.Name("type").Value("map").Name("value").BeginObject();`);
  lines.push(`      foreach (System.Collections.DictionaryEntry e in dict) {`);
  lines.push(`        writer.Name(System.Convert.ToString(e.Key, System.Globalization.CultureInfo.InvariantCulture) ?? "");`);
  lines.push(`        WriteValue(writer, e.Value);`);
  lines.push(`      }`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value is System.Collections.IEnumerable enumerable) {`);
  lines.push(`      writer.BeginObject();`);
  lines.push(`      writer.Name("type").Value("list").Name("value").BeginArray();`);
  lines.push(`      foreach (var item in enumerable) WriteValue(writer, item);`);
  lines.push(`      writer.EndArray();`);
  lines.push(`      writer.EndObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    writer.BeginObject();`);
  lines.push(`    writer.Name("type").Value("string").Name("value").Value(System.Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture) ?? "");`);
  lines.push(`    writer.EndObject();`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(csharpJsonWriterSource());
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/** 从 TypedValue 生成 C# 字面量。 */
export function csharpLiteral(value: TypedValue): string {
  switch (value.type) {
    case "string":
      return csharpStringLiteral(value.value);
    case "number":
      return csharpNumberLiteral(value.value);
    case "boolean":
      return value.value ? "true" : "false";
    case "null":
      return "null";
    case "list":
      return csharpListLiteral(value.value);
    case "map":
      return csharpMapLiteral(value.value);
  }
}

/**
 * 从 TypedValue 推导 C# 类型名(string/int/long/double/bool/List<...>/Dictionary<string,...>)。
 * 内部复用 csharpCommonType(单值即公共类型的特例);含 null 元素的集合回退 object?。
 */
export function csharpValueTypeName(value: TypedValue): string {
  switch (value.type) {
    case "string":
      return "string";
    case "number":
      return csharpNumberTypeName(value.value);
    case "boolean":
      return "bool";
    case "null":
      return "object?";
    case "list": {
      const items = value.value;
      if (items.length === 0) return "object?";
      const inner = items.some((v) => v.type === "null") ? "object?" : csharpCommonType(items);
      return inner === "object?" ? "object?" : `List<${inner}>`;
    }
    case "map": {
      const values = Object.values(value.value);
      if (values.length === 0) return "object?";
      const inner = values.some((v) => v.type === "null") ? "object?" : csharpCommonType(values);
      return inner === "object?" ? "object?" : `Dictionary<string, ${inner}>`;
    }
  }
}

function csharpListLiteral(items: TypedValue[]): string {
  if (items.length === 0) return "new List<object?>()";
  // 含 null 元素时值类型不能容纳 null,必须回退 object?;否则取公共类型。
  const itemType = items.some((v) => v.type === "null") ? "object?" : csharpCommonType(items);
  const inner = items.map(csharpLiteral).join(", ");
  return `new List<${itemType}>{ ${inner} }`;
}

function csharpMapLiteral(entries: Record<string, TypedValue>): string {
  const keys = Object.keys(entries);
  if (keys.length === 0) return "new Dictionary<string, object?>()";
  const values = keys.map((k) => entries[k] as TypedValue);
  const valueType = values.some((v) => v.type === "null") ? "object?" : csharpCommonType(values);
  const inner = keys.map((k) => `[${csharpStringLiteral(k)}] = ${csharpLiteral(entries[k] as TypedValue)}`).join(", ");
  return `new Dictionary<string, ${valueType}>{ ${inner} }`;
}

/**
 * 公共类型推导(与 Java 侧 javaLiteralType 口径对齐):
 * 合并所有非 null 元素的类型;全部相同 → 该类型;number 系(int/long/double)混合 → "double";
 * 其余异质 / 空 / 全 null → "object?"。
 */
function csharpCommonType(values: TypedValue[]): string {
  const nonNull = values.filter((v) => v.type !== "null");
  if (nonNull.length === 0) return "object?";
  return nonNull.map(csharpValueTypeName).reduce(mergeCommonType);
}

function mergeCommonType(a: string, b: string): string {
  if (a === b) return a;
  if (isCSharpNumberType(a) && isCSharpNumberType(b)) return "double";
  return "object?";
}

function isCSharpNumberType(t: string): boolean {
  return t === "int" || t === "long" || t === "double";
}

function csharpStringLiteral(value: string): string {
  let result = '"';
  for (const ch of value) {
    switch (ch) {
      case '"':
        result += '\\"';
        break;
      case "\\":
        result += "\\\\";
        break;
      case "\n":
        result += "\\n";
        break;
      case "\r":
        result += "\\r";
        break;
      case "\t":
        result += "\\t";
        break;
      default:
        if (ch.charCodeAt(0) < 0x20) {
          result += `\\u${ch.charCodeAt(0).toString(16).padStart(4, "0")}`;
        } else {
          result += ch;
        }
    }
  }
  return `${result}"`;
}

function csharpNumberLiteral(value: number): string {
  if (Number.isNaN(value)) return "double.NaN";
  if (value === Infinity) return "double.PositiveInfinity";
  if (value === -Infinity) return "double.NegativeInfinity";
  if (Number.isInteger(value) && Math.abs(value) <= 2147483647) return String(value);
  // 注意:long.MaxValue(9223372036854775807)在 JS 中舍入为 2^63,故用 < 而非 <=;否则 ±2^63 会生成
  // 9223372036854775808L(超出 long 范围,CS1021)。±2^63 落入下方 double 指数分支。
  if (Number.isInteger(value) && Math.abs(value) < 9223372036854775807) return `${String(value)}L`;
  // 其余(超出 long 的整数与浮点):模拟 double.ToString("R", InvariantCulture),
  // 如 1E+20 / 1.5 / 2.5E-07,均为合法 C# double 字面量。
  return csharpRoundTrip(value);
}

/** number 的 C# 类型名:int(≤ int.MaxValue)/ long(≤ long.MaxValue)/ double。 */
function csharpNumberTypeName(value: number): "int" | "long" | "double" {
  if (Number.isInteger(value) && Math.abs(value) <= 2147483647) return "int";
  // 同 csharpNumberLiteral:9223372036854775807 字面量舍入为 2^63,必须用 <,±2^63 归 double。
  if (Number.isInteger(value) && Math.abs(value) < 9223372036854775807) return "long";
  return "double";
}

/** 模拟 C# double.ToString("R", InvariantCulture):大数量级用 E±dd 指数形式(指数至少两位),其余十进制。 */
function csharpRoundTrip(value: number): string {
  const abs = Math.abs(value);
  if (value !== 0 && (abs >= 1e7 || abs < 1e-3)) {
    const [mantissa, expPart] = value.toExponential().split("e");
    const sign = expPart.startsWith("-") ? "-" : "+";
    const digits = expPart.replace(/^[+-]/, "").padStart(2, "0");
    return `${mantissa}E${sign}${digits}`;
  }
  return String(value);
}

/**
 * 内嵌 JsonWriter:容器状态逗号管理(kinds/counts/depth,Name 管对象成员逗号、ItemPrefix 管数组元素逗号)。
 * 注意:C# 中 `out` 是保留关键字,变量名统一用 writer;`\u` 转义必须写成 `"\\u"`(TS 中 `\\\\u`),否则生成非法 C# 字面量。
 */
function csharpJsonWriterSource(): string {
  return [
    `  sealed class JsonWriter {`,
    `    private readonly System.IO.TextWriter writer;`,
    `    private readonly char[] kinds = new char[64];`,
    `    private readonly int[] counts = new int[64];`,
    `    private int depth = 0;`,
    `    public JsonWriter(System.IO.TextWriter writer) { this.writer = writer; }`,
    `    public JsonWriter BeginObject() { ItemPrefix(); writer.Write("{"); kinds[++depth] = '{'; counts[depth] = 0; return this; }`,
    `    public JsonWriter EndObject() { writer.Write("}"); depth--; return this; }`,
    `    public JsonWriter BeginArray() { ItemPrefix(); writer.Write("["); kinds[++depth] = '['; counts[depth] = 0; return this; }`,
    `    public JsonWriter EndArray() { writer.Write("]"); depth--; return this; }`,
    `    public JsonWriter Name(string name) {`,
    `      if (kinds[depth] == '{' && counts[depth] > 0) writer.Write(",");`,
    `      counts[depth]++;`,
    `      writer.Write("\\\""); writer.Write(Escape(name)); writer.Write("\\\":");`,
    `      return this;`,
    `    }`,
    `    private void ItemPrefix() {`,
    `      if (depth > 0 && kinds[depth] == '[') {`,
    `        if (counts[depth] > 0) writer.Write(",");`,
    `        counts[depth]++;`,
    `      }`,
    `    }`,
    `    public JsonWriter ValueNull() { writer.Write("null"); return this; }`,
    `    public JsonWriter Value(string value) { writer.Write("\\\""); writer.Write(Escape(value)); writer.Write("\\\""); return this; }`,
    `    public JsonWriter Value(long value) { writer.Write(System.Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture)); return this; }`,
    `    public JsonWriter Value(bool value) { writer.Write(value ? "true" : "false"); return this; }`,
    `    public JsonWriter Value(double value) {`,
    `      if (double.IsNaN(value)) { writer.Write("\\\"NaN\\\""); return this; }`,
    `      if (double.IsInfinity(value)) { writer.Write(value > 0 ? "\\\"Infinity\\\"" : "\\\"-Infinity\\\""); return this; }`,
    `      writer.Write(value.ToString("R", System.Globalization.CultureInfo.InvariantCulture));`,
    `      return this;`,
    `    }`,
    `    public void Flush() { writer.Flush(); }`,
    `    private static string Escape(string value) {`,
    `      var sb = new System.Text.StringBuilder();`,
    `      foreach (var c in value) {`,
    `        switch (c) {`,
    `          case '"': sb.Append("\\\\\\\""); break;`,
    `          case '\\\\': sb.Append("\\\\\\\\"); break;`,
    `          case '\\n': sb.Append("\\\\n"); break;`,
    `          case '\\r': sb.Append("\\\\r"); break;`,
    `          case '\\t': sb.Append("\\\\t"); break;`,
    `          case '\\b': sb.Append("\\\\b"); break;`,
    `          case '\\f': sb.Append("\\\\f"); break;`,
    `          default:`,
    `            if (c < 0x20) { sb.Append("\\\\u").Append(((int)c).ToString("x4")); } else { sb.Append(c); }`,
    `            break;`,
    `        }`,
    `      }`,
    `      return sb.ToString();`,
    `    }`,
    `  }`,
  ].join("\n");
}
