import { type TestDescription, type TypedValue } from "../description.js";
import { driverClassName } from "./driver-codegen.js";

export function generateJavaDriver(description: TestDescription): string {
  const className = driverClassName(description);
  const lines: string[] = [];
  lines.push(`// Generated by @forexplore/translation-verifier. Do not edit.`);
  lines.push(`import java.util.Arrays;`);
  lines.push(`import java.util.List;`);
  lines.push(`import java.util.Map;`);
  lines.push(`public class ${className} {`);
  lines.push(`  public static void main(String[] args) throws Exception {`);
  lines.push(`    JsonWriter out = new JsonWriter(System.out);`);
  lines.push(`    out.beginObject().name("results").beginArray();`);
  description.cases.forEach((c, i) => lines.push(`    case_${String(i).padStart(3, "0")}(out);`));
  lines.push(`    out.endArray().endObject().flush();`);
  lines.push(`  }`);
  lines.push(``);

  description.cases.forEach((c, i) => {
    const methodName = `case_${String(i).padStart(3, "0")}`;
    lines.push(`  static void ${methodName}(JsonWriter out) throws Exception {`);
    lines.push(`    out.beginObject().name("caseId").value(${JSON.stringify(c.id)});`);
    const args = c.inputs.map(javaLiteral).join(", ");
    const call = description.target.isStatic
      ? `${description.target.className}.${description.target.method}(${args})`
      : `new ${description.target.className}(${description.target.constructorArgs.map(javaLiteral).join(", ")}).${description.target.method}(${args})`;
    lines.push(`    try {`);
    lines.push(`      Object r = ${call};`);
    lines.push(`      out.name("outcome").value("return");`);
    lines.push(`      out.name("returnValue");`);
    lines.push(`      writeValue(out, r);`);
    lines.push(`    } catch (Throwable t) {`);
    lines.push(`      out.name("outcome").value("exception");`);
    lines.push(`      out.name("exceptionType").value(t.getClass().getSimpleName());`);
    lines.push(`      out.name("exceptionMessage").value(t.getMessage() == null ? "" : t.getMessage());`);
    lines.push(`    }`);
    lines.push(`    out.endObject();`);
    lines.push(`  }`);
    lines.push(``);
  });

  lines.push(`  static void writeValue(JsonWriter out, Object value) throws Exception {`);
  lines.push(`    if (value == null) { out.beginObject(); out.name("type").value("null").name("value").valueNull(); out.endObject(); return; }`);
  lines.push(`    if (value instanceof String) { out.beginObject(); out.name("type").value("string").name("value").value((String) value); out.endObject(); return; }`);
  lines.push(`    if (value instanceof Byte) {
      // byte 在 Java 是有符号(-128..127),C# byte 是无符号(0..255);输出无符号值避免跨语言字节数组差分误报。
      out.beginObject();
      out.name("type").value("number").name("value").value(((Byte) value).byteValue() & 0xFF);
      out.endObject();
      return;
    }
    if (value instanceof Number) {`);
  lines.push(`      out.beginObject();`);
  lines.push(`      out.name("type").value("number").name("value").value(((Number) value).doubleValue());`);
  lines.push(`      out.endObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value instanceof Boolean) { out.beginObject(); out.name("type").value("boolean").name("value").value(((Boolean) value).booleanValue()); out.endObject(); return; }`);
  lines.push(`    if (value instanceof java.util.Map) {`);
  lines.push(`      out.beginObject();`);
  lines.push(`      out.name("type").value("map").name("value").beginObject();`);
  lines.push(`      for (Object entryObj : ((java.util.Map<?, ?>) value).entrySet()) {`);
  lines.push(`        java.util.Map.Entry<?, ?> entry = (java.util.Map.Entry<?, ?>) entryObj;`);
  lines.push(`        out.name(String.valueOf(entry.getKey()));`);
  lines.push(`        writeValue(out, entry.getValue());`);
  lines.push(`      }`);
  lines.push(`      out.endObject();`);
  lines.push(`      out.endObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value instanceof Iterable || value.getClass().isArray()) {`);
  lines.push(`      out.beginObject();`);
  lines.push(`      out.name("type").value("list").name("value").beginArray();`);
  lines.push(`      if (value instanceof Iterable) {`);
  lines.push(`        for (Object item : (Iterable<?>) value) writeValue(out, item);`);
  lines.push(`      } else {`);
  lines.push(`        int len = java.lang.reflect.Array.getLength(value);`);
  lines.push(`        for (int i = 0; i < len; i++) writeValue(out, java.lang.reflect.Array.get(value, i));`);
  lines.push(`      }`);
  lines.push(`      out.endArray();`);
  lines.push(`      out.endObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    out.beginObject();`);
  lines.push(`    out.name("type").value("string").name("value").value(String.valueOf(value));`);
  lines.push(`    out.endObject();`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(javaJsonWriterSource());
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

export function javaLiteral(value: TypedValue): string {
  switch (value.type) {
    case "string":
      return JSON.stringify(value.value);
    case "number":
      return javaNumberLiteral(value.value);
    case "boolean":
      return value.value ? "true" : "false";
    case "null":
      return "null";
    case "list": {
      const items = value.value;
      if (items.length === 0) return "List.of()";
      if (items.some((item) => item.type === "null")) {
        return `Arrays.<${javaLiteralType(items)}>asList(${items.map(javaLiteral).join(", ")})`;
      }
      return `List.of(${items.map(javaLiteral).join(", ")})`;
    }
    case "map": {
      const entries = Object.entries(value.value);
      if (entries.length === 0) return "Map.of()";
      if (entries.some(([, v]) => v.type === "null")) {
        const valueType = javaLiteralType(entries.map(([, v]) => v));
        const puts = entries.map(([k, v]) => `put(${JSON.stringify(k)}, ${javaLiteral(v)})`).join("; ");
        return `new java.util.HashMap<String, ${valueType}>() {{ ${puts}; }}`;
      }
      return `Map.ofEntries(${entries
        .map(([k, v]) => `Map.entry(${JSON.stringify(k)}, ${javaLiteral(v)})`)
        .join(", ")})`;
    }
  }
}

function javaLiteralType(values: TypedValue[]): string {
  const nonNull = values.filter((v) => v.type !== "null");
  if (nonNull.length === 0) return "Object";
  return nonNull.map(elementType).reduce(commonType);
}

function elementType(value: TypedValue): string {
  switch (value.type) {
    case "string": return "String";
    case "number": return javaNumberTypeName(value.value);
    case "boolean": return "Boolean";
    case "null": return "Object";
    case "list": return `List<${javaLiteralType(value.value)}>`;
    case "map": {
      const values = Object.values(value.value);
      if (values.length === 0) return "Map<String, Object>";
      return `Map<String, ${javaLiteralType(values)}>`;
    }
  }
}

function commonType(a: string, b: string): string {
  if (a === b) return a;
  if (isNumberType(a) && isNumberType(b)) return "Number";
  return "Object";
}

function isNumberType(t: string): boolean {
  return t === "Integer" || t === "Long" || t === "Double" || t === "Number";
}

/** number 的 Java 装箱类型名:Integer(≤ int.MaxValue)/ Long(≤ long.MaxValue)/ Double。 */
function javaNumberTypeName(value: number): "Integer" | "Long" | "Double" {
  if (Number.isInteger(value) && Math.abs(value) <= 2147483647) return "Integer";
  // 同 javaNumberLiteral:9223372036854775807 字面量舍入为 2^63,必须用 <,±2^63 归 Double。
  if (Number.isInteger(value) && Math.abs(value) < 9223372036854775807) return "Long";
  return "Double";
}

function javaNumberLiteral(value: number): string {
  if (Number.isNaN(value)) return "Double.NaN";
  if (value === Infinity) return "Double.POSITIVE_INFINITY";
  if (value === -Infinity) return "Double.NEGATIVE_INFINITY";
  if (Number.isInteger(value) && Math.abs(value) <= 2147483647) return String(value);
  // 注意:long.MaxValue(9223372036854775807)在 JS 中舍入为 2^63,故用 < 而非 <=;否则 ±2^63 会生成
  // 9223372036854775808L(超出 long 范围,integer number too large)。±2^63 落入下方 double 分支。
  if (Number.isInteger(value) && Math.abs(value) < 9223372036854775807) return `${String(value)}L`;
  if (Number.isInteger(value)) return javaDoubleLiteral(value);
  return String(value);
}

/** Java Double.toString 口径的指数形式(1e20 → "1.0E20"):超出 long 的整数走这里。 */
function javaDoubleLiteral(value: number): string {
  const [mantissa, expPart] = value.toExponential().split("e");
  const m = mantissa.includes(".") ? mantissa : `${mantissa}.0`;
  return `${m}E${Number(expPart)}`;
}

function javaJsonWriterSource(): string {
  return [
    `  /** Minimal JSON writer with container-state comma management. */`,
    `  static final class JsonWriter {`,
    `    private final Appendable out;`,
    `    private final char[] kinds = new char[64];`,
    `    private final int[] counts = new int[64];`,
    `    private int depth = 0;`,
    `    JsonWriter(Appendable out) { this.out = out; }`,
    `    JsonWriter beginObject() throws Exception { itemPrefix(); out.append("{"); kinds[++depth] = '{'; counts[depth] = 0; return this; }`,
    `    JsonWriter endObject() throws Exception { out.append("}"); depth--; return this; }`,
    `    JsonWriter beginArray() throws Exception { itemPrefix(); out.append("["); kinds[++depth] = '['; counts[depth] = 0; return this; }`,
    `    JsonWriter endArray() throws Exception { out.append("]"); depth--; return this; }`,
    `    JsonWriter name(String name) throws Exception {`,
    `      if (kinds[depth] == '{' && counts[depth] > 0) out.append(",");`,
    `      counts[depth]++;`,
    `      out.append("\\"").append(escape(name)).append("\\":");`,
    `      return this;`,
    `    }`,
    `    private void itemPrefix() throws Exception {`,
    `      if (depth > 0 && kinds[depth] == '[') {`,
    `        if (counts[depth] > 0) out.append(",");`,
    `        counts[depth]++;`,
    `      }`,
    `    }`,
    `    JsonWriter valueNull() throws Exception { out.append("null"); return this; }`,
    `    JsonWriter value(String value) throws Exception { out.append("\\"").append(escape(value)).append("\\""); return this; }`,
    `    JsonWriter value(boolean value) throws Exception { out.append(value ? "true" : "false"); return this; }`,
    `    JsonWriter value(int value) throws Exception { out.append(Integer.toString(value)); return this; }`,
    `    JsonWriter value(long value) throws Exception { out.append(Long.toString(value)); return this; }`,
    `    JsonWriter value(double value) throws Exception {`,
    `      if (Double.isNaN(value)) { out.append("\\"NaN\\""); return this; }`,
    `      if (Double.isInfinite(value)) { out.append(value > 0 ? "\\"Infinity\\"" : "\\"-Infinity\\""); return this; }`,
    `      out.append(Double.toString(value));`,
    `      return this;`,
    `    }`,
    `    JsonWriter flush() throws Exception { if (out instanceof java.io.Flushable) ((java.io.Flushable) out).flush(); return this; }`,
    `    static String escape(String value) {`,
    `      StringBuilder sb = new StringBuilder();`,
    `      for (int i = 0; i < value.length(); i++) {`,
    `        char c = value.charAt(i);`,
    `        switch (c) {`,
    `          case '"': sb.append("\\\\\\""); break;`,
    `          case '\\\\': sb.append("\\\\\\\\"); break;`,
    `          case '\\n': sb.append("\\\\n"); break;`,
    `          case '\\r': sb.append("\\\\r"); break;`,
    `          case '\\t': sb.append("\\\\t"); break;`,
    `          case '\\b': sb.append("\\\\b"); break;`,
    `          case '\\f': sb.append("\\\\f"); break;`,
    `          default:`,
    `            if (c < 0x20) { sb.append(String.format("\\\\u%04x", (int) c)); } else { sb.append(c); }`,
    `        }`,
    `      }`,
    `      return sb.toString();`,
    `    }`,
    `  }`,
  ].join("\n");
}
