import { createHash } from "node:crypto";
import { canonicalDescriptionJson, type TestDescription, type TypedValue } from "../description.js";

export function driverClassName(description: TestDescription): string {
  const hash = createHash("sha256").update(canonicalDescriptionJson(description), "utf8").digest("hex");
  return `Driver_${hash.slice(0, 8)}`;
}

export function generateJavaDriver(description: TestDescription): string {
  const className = driverClassName(description);
  const lines: string[] = [];
  lines.push(`// Generated by @forexplore/translation-verifier. Do not edit.`);
  // javaLiteral 生成 List.of / Map.ofEntries / Map.entry,需导入 java.util 以保证驱动可独立编译。
  lines.push(`import java.util.List;`);
  lines.push(`import java.util.Map;`);
  lines.push(``);
  lines.push(`public class ${className} {`);
  lines.push(`  public static void main(String[] args) throws Exception {`);
  lines.push(`    JsonWriter out = new JsonWriter(System.out);`);
  lines.push(`    out.beginObject().name("results").beginArray();`);
  description.cases.forEach((c, i) => lines.push(`    case_${String(i).padStart(3, "0")}(out);`));
  lines.push(`    out.endArray().endObject().flush();`);
  lines.push(`  }`);
  lines.push(``);

  description.cases.forEach((c, i) => {
    const methodName = `case_${String(i).padStart(3, "0")}`;
    lines.push(`  static void ${methodName}(JsonWriter out) throws Exception {`);
    lines.push(`    out.beginObject().name("caseId").value(${JSON.stringify(c.id)});`);
    const args = c.inputs.map(javaLiteral).join(", ");
    const call = description.target.isStatic
      ? `${description.target.className}.${description.target.method}(${args})`
      : `new ${description.target.className}(${description.target.constructorArgs.map(javaLiteral).join(", ")}).${description.target.method}(${args})`;
    lines.push(`    try {`);
    lines.push(`      Object r = ${call};`);
    lines.push(`      out.name("outcome").value("return");`);
    lines.push(`      out.name("returnValue");`);
    lines.push(`      writeValue(out, r);`);
    lines.push(`    } catch (Throwable t) {`);
    lines.push(`      out.name("outcome").value("exception");`);
    lines.push(`      out.name("exceptionType").value(t.getClass().getSimpleName());`);
    lines.push(`      out.name("exceptionMessage").value(t.getMessage() == null ? "" : t.getMessage());`);
    lines.push(`    }`);
    lines.push(`    out.endObject();`);
    lines.push(`  }`);
    lines.push(``);
  });

  lines.push(`  static void writeValue(JsonWriter out, Object value) throws Exception {`);
  lines.push(`    if (value == null) { out.valueNull(); return; }`);
  lines.push(`    if (value instanceof String) { out.value((String) value); return; }`);
  lines.push(`    if (value instanceof Number) {`);
  lines.push(`      out.name("type").value("number").name("value").value(((Number) value).doubleValue());`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value instanceof Boolean) { out.name("type").value("boolean").name("value").value(value.toString()); return; }`);
  lines.push(`    if (value instanceof java.util.Map) {`);
  lines.push(`      out.name("type").value("map").name("value").beginObject();`);
  lines.push(`      for (Object entryObj : ((java.util.Map<?, ?>) value).entrySet()) {`);
  lines.push(`        java.util.Map.Entry<?, ?> entry = (java.util.Map.Entry<?, ?>) entryObj;`);
  lines.push(`        out.name(String.valueOf(entry.getKey()));`);
  lines.push(`        writeValue(out, entry.getValue());`);
  lines.push(`      }`);
  lines.push(`      out.endObject();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    if (value instanceof Iterable || value.getClass().isArray()) {`);
  lines.push(`      out.name("type").value("list").name("value").beginArray();`);
  lines.push(`      if (value instanceof Iterable) {`);
  lines.push(`        for (Object item : (Iterable<?>) value) writeValue(out, item);`);
  lines.push(`      } else {`);
  lines.push(`        int len = java.lang.reflect.Array.getLength(value);`);
  lines.push(`        for (int i = 0; i < len; i++) writeValue(out, java.lang.reflect.Array.get(value, i));`);
  lines.push(`      }`);
  lines.push(`      out.endArray();`);
  lines.push(`      return;`);
  lines.push(`    }`);
  lines.push(`    out.name("type").value("string").name("value").value(String.valueOf(value));`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(javaJsonWriterSource());
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

export function javaLiteral(value: TypedValue): string {
  switch (value.type) {
    case "string":
      return JSON.stringify(value.value);
    case "number":
      return javaNumberLiteral(value.value);
    case "boolean":
      return value.value ? "true" : "false";
    case "null":
      return "null";
    case "list":
      return value.value.length === 0 ? "List.of()" : `List.of(${value.value.map(javaLiteral).join(", ")})`;
    case "map": {
      const entries = Object.entries(value.value);
      if (entries.length === 0) return "Map.of()";
      return `Map.ofEntries(${entries
        .map(([k, v]) => `Map.entry(${JSON.stringify(k)}, ${javaLiteral(v)})`)
        .join(", ")})`;
    }
  }
}

function javaNumberLiteral(value: number): string {
  if (Number.isNaN(value)) return "Double.NaN";
  if (value === Infinity) return "Double.POSITIVE_INFINITY";
  if (value === -Infinity) return "Double.NEGATIVE_INFINITY";
  if (Number.isInteger(value)) return String(value);
  return String(value);
}

function javaJsonWriterSource(): string {
  return [
    `  /** Minimal JSON writer with chained methods; emits normalized CaseResult payloads. */`,
    `  static final class JsonWriter {`,
    `    private final Appendable out;`,
    `    JsonWriter(Appendable out) { this.out = out; }`,
    `    JsonWriter beginObject() throws Exception { out.append("{"); return this; }`,
    `    JsonWriter endObject() throws Exception { out.append("}"); return this; }`,
    `    JsonWriter beginArray() throws Exception { out.append("["); return this; }`,
    `    JsonWriter endArray() throws Exception { out.append("]"); return this; }`,
    `    JsonWriter name(String name) throws Exception { out.append("\\"").append(escape(name)).append("\\":"); return this; }`,
    `    JsonWriter valueNull() throws Exception { out.append("null"); return this; }`,
    `    JsonWriter value(String value) throws Exception { out.append("\\"").append(escape(value)).append("\\""); return this; }`,
    `    JsonWriter value(boolean value) throws Exception { out.append(value ? "true" : "false"); return this; }`,
    `    JsonWriter value(int value) throws Exception { out.append(Integer.toString(value)); return this; }`,
    `    JsonWriter value(long value) throws Exception { out.append(Long.toString(value)); return this; }`,
    `    JsonWriter value(double value) throws Exception {`,
    `      if (Double.isNaN(value)) { out.append("\\"NaN\\""); return this; }`,
    `      if (Double.isInfinite(value)) { out.append(value > 0 ? "\\"Infinity\\"" : "\\"-Infinity\\""); return this; }`,
    `      out.append(Double.toString(value));`,
    `      return this;`,
    `    }`,
    `    JsonWriter flush() throws Exception { if (out instanceof java.io.Flushable) ((java.io.Flushable) out).flush(); return this; }`,
    `    static String escape(String value) {`,
    `      StringBuilder sb = new StringBuilder();`,
    `      for (int i = 0; i < value.length(); i++) {`,
    `        char c = value.charAt(i);`,
    `        switch (c) {`,
    `          case '"': sb.append("\\\\\\""); break;`,
    `          case '\\\\': sb.append("\\\\\\\\"); break;`,
    `          case '\\n': sb.append("\\\\n"); break;`,
    `          case '\\r': sb.append("\\\\r"); break;`,
    `          case '\\t': sb.append("\\\\t"); break;`,
    `          case '\\b': sb.append("\\\\b"); break;`,
    `          case '\\f': sb.append("\\\\f"); break;`,
    `          default:`,
    `            if (c < 0x20) { sb.append(String.format("\\\\u%04x", (int) c)); } else { sb.append(c); }`,
    `        }`,
    `      }`,
    `      return sb.toString();`,
    `    }`,
    `  }`,
  ].join("\n");
}
