import type { TestDescription, TypedValue } from "../description.js";
import { type SourceInvocation } from "./source-invocation.js";

export function generatePythonDriver(description: TestDescription, source: SourceInvocation): string {
  if (!source.module) throw new Error("Python source driver requires source.module.");
  const lines: string[] = [];
  lines.push("# Generated by @forexplore/translation-verifier. Do not edit.");
  lines.push("import importlib");
  lines.push("import json");
  lines.push("");
  lines.push("def to_typed(value):");
  lines.push("    if value is None: return {'type': 'null', 'value': None}");
  lines.push("    if isinstance(value, bool): return {'type': 'boolean', 'value': value}");
  lines.push("    if isinstance(value, str): return {'type': 'string', 'value': value}");
  lines.push("    if isinstance(value, (int, float)) and not isinstance(value, bool): return {'type': 'number', 'value': value}");
  lines.push("    if isinstance(value, (list, tuple, set)): return {'type': 'list', 'value': [to_typed(item) for item in value]}");
  lines.push("    if isinstance(value, dict): return {'type': 'map', 'value': {str(key): to_typed(item) for key, item in value.items()}}");
  lines.push("    return {'type': 'string', 'value': str(value)}");
  lines.push("");
  lines.push(`module = importlib.import_module(${JSON.stringify(source.module)})`);
  lines.push(source.className ? `owner = getattr(module, ${JSON.stringify(source.className)})` : "owner = module");
  if (!source.isStatic && source.className) {
    lines.push(`receiver = owner(*${pythonLiteral(source.constructorArgs)})`);
  }
  lines.push("results = []");
  for (const testCase of description.cases) {
    const receiver = source.isStatic || !source.className ? "owner" : "receiver";
    lines.push("try:");
    lines.push(`    value = ${receiver}.${source.method}(*${pythonLiteral(testCase.inputs)})`);
    lines.push(`    results.append({'caseId': ${JSON.stringify(testCase.id)}, 'outcome': 'return', 'returnValue': to_typed(value)})`);
    lines.push("except BaseException as error:");
    lines.push(`    results.append({'caseId': ${JSON.stringify(testCase.id)}, 'outcome': 'exception', 'exceptionType': type(error).__name__, 'exceptionMessage': str(error)})`);
  }
  lines.push("print(json.dumps({'results': results}, ensure_ascii=True, separators=(',', ':')))");
  return `${lines.join("\n")}\n`;
}

function pythonLiteral(values: TypedValue[]): string {
  return `json.loads(${JSON.stringify(JSON.stringify(values.map(plainValue)))})`;
}

function plainValue(value: TypedValue): unknown {
  switch (value.type) {
    case "string":
    case "number":
    case "boolean":
    case "null":
      return value.value;
    case "list":
      return value.value.map(plainValue);
    case "map":
      return Object.fromEntries(Object.entries(value.value).map(([key, item]) => [key, plainValue(item)]));
  }
}
