import type { TestDescription, TypedValue } from "../description.js";
import { type SourceInvocation } from "./source-invocation.js";

export function generateTypeScriptDriver(description: TestDescription, source: SourceInvocation): string {
  if (!source.module) throw new Error("TypeScript source driver requires source.module.");
  const modulePath = normalizeModulePath(source.module);
  const lines: string[] = [];
  lines.push("// Generated by @forexplore/translation-verifier. Do not edit.");
  lines.push(`import * as sourceModule from ${JSON.stringify(`./${modulePath}`)};`);
  lines.push("");
  lines.push("function toTyped(value: unknown): unknown {");
  lines.push("  if (value === null || value === undefined) return { type: 'null', value: null };");
  lines.push("  if (typeof value === 'string') return { type: 'string', value };");
  lines.push("  if (typeof value === 'number') return { type: 'number', value };");
  lines.push("  if (typeof value === 'boolean') return { type: 'boolean', value };");
  lines.push("  if (Array.isArray(value) || value instanceof Set) return { type: 'list', value: [...value].map(toTyped) };");
  lines.push("  if (value instanceof Map) return { type: 'map', value: Object.fromEntries([...value].map(([key, item]) => [String(key), toTyped(item)])) };");
  lines.push("  if (typeof value === 'object') return { type: 'map', value: Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, toTyped(item)])) };");
  lines.push("  return { type: 'string', value: String(value) };");
  lines.push("}");
  lines.push("");
  lines.push("async function main(): Promise<void> {");
  lines.push(source.className ? `  const owner: any = (sourceModule as any)[${JSON.stringify(source.className)}];` : "  const owner: any = sourceModule;");
  if (!source.isStatic && source.className) {
    lines.push(`  const receiver: any = new owner(...${typescriptLiteral(source.constructorArgs)});`);
  }
  lines.push("  const results: unknown[] = [];");
  for (const testCase of description.cases) {
    const receiver = source.isStatic || !source.className ? "owner" : "receiver";
    lines.push("  try {");
    lines.push(`    const value = await ${receiver}[${JSON.stringify(source.method)}](...${typescriptLiteral(testCase.inputs)});`);
    lines.push(`    results.push({ caseId: ${JSON.stringify(testCase.id)}, outcome: 'return', returnValue: toTyped(value) });`);
    lines.push("  } catch (error) {");
    lines.push("    const exception = error instanceof Error ? error : new Error(String(error));");
    lines.push(`    results.push({ caseId: ${JSON.stringify(testCase.id)}, outcome: 'exception', exceptionType: exception.constructor?.name ?? 'Error', exceptionMessage: String(exception.message ?? '') });`);
    lines.push("  }");
  }
  lines.push("  process.stdout.write(JSON.stringify({ results }));");
  lines.push("}");
  lines.push("");
  lines.push("void main();");
  return `${lines.join("\n")}\n`;
}

function normalizeModulePath(module: string): string {
  const normalized = module.replace(/\\/g, "/").replace(/^\.\//, "");
  if (!normalized || normalized.startsWith("/") || normalized.split("/").includes("..")) {
    throw new Error("TypeScript source.module must be a workspace-relative path.");
  }
  return normalized.endsWith(".ts") ? normalized : `${normalized}.ts`;
}

function typescriptLiteral(values: TypedValue[]): string {
  return JSON.stringify(values.map(plainValue));
}

function plainValue(value: TypedValue): unknown {
  switch (value.type) {
    case "string":
    case "number":
    case "boolean":
    case "null":
      return value.value;
    case "list":
      return value.value.map(plainValue);
    case "map":
      return Object.fromEntries(Object.entries(value.value).map(([key, item]) => [key, plainValue(item)]));
  }
}
